spring.application.name=com.claims.claimsservice
server.port=8282
spring.datasource.url=jdbc:mysql://localhost:3306/claim processing
spring.datasource.username=root
spring.datasource.password=shreya
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
policy.service.host=http://localhost:8181
policy.service.status.url=/policy/processing/service/getPolicyStatus/
kafka.topic.claim-created=claim-created-v2
kafka.bootstrap-servers=localhost:9092
kafka.consumer.group-id=claim-service-group
kafka.topic.claim-processed=kafka.topic.claim-processed